language: R
sudo: false
cache: packages
warnings_are_errors: false

r:
  - release
  - oldrel
  - devel

r_packages:
  - covr
  
after_success:
  - Rscript -e "covr::codecov()"

notifications:
  email:
    on_success: change
    on_failure: change
